# This file has been generated by node2nix 1.6.0. Do not edit!

#{pkgs, purescript, nodejs}:
#{pkgs ? import <nixpkgs> {
    #inherit system;
  #}, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-6_x", purescript}:
{pkgs , system , nodejs ? pkgs."nodejs-10_x", purescript}:

let
  src = pkgs.fetchFromGitHub {
    owner = "kritzcreek";
    repo = "pscid";
    rev = "v2.6.0";
    sha256 = "1f54441b8cfs9fmd8i29l20gv5qw1w2dcj40pp61vpl25ggqh4yc";
  };
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv python2 utillinux runCommand writeTextFile;
    inherit nodejs;
    libtool = if pkgs.stdenv.isDarwin then pkgs.darwin.cctools else null;
  };
  pscidBowerDeps = import ./pscid-bower-deps.nix {
    inherit pkgs src;
  };
in
import ./node-packages.nix {
  inherit (pkgs) fetchurl fetchgit fetchFromGitHub;
  inherit nodeEnv;
  inherit pkgs;
  inherit src;
  pulp = pkgs.nodePackages_10_x.pulp;
  globalBuildInputs =
  with pkgs;
  [
    purescript
    nodePackages_10_x.node-gyp
    nodePackages_10_x.node-pre-gyp
    nodePackages_10_x.node-gyp-build
  ];
  bowerDeps = pscidBowerDeps;
}
