# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "i915" "intel_agp" "rtsx_pci_sdmmc" ];
  boot.loader.grub.zfsSupport = true;
  boot.initrd.kernelModules = [ ];
  boot.supportedFilesystems = [ "zfs" ];
  boot.initrd.supportedFilesystems = [ "zfs" ];
  # acpi_call only for laptops
  boot.kernelModules = [ "kvm-intel" "acpi_call" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ acpi_call ];

  fileSystems."/" =
    { device = "master/local/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6145-E25E";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "master/local/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "master/safe/home";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "master/safe/persist";
      fsType = "zfs";
    };

  fileSystems."/tmp" =
    { device = "master/local/tmp";
      fsType = "zfs";
    };

  swapDevices = [ ];


  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.nvidiaOptimus.disable = true;
}
