# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.loader.efi.canTouchEfiVariables = true;
  boot.kernelParams = pkgs.lib.mkDefault [ "acpi_rev_override" ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "i915" "intel_agp" "rtsx_pci_sdmmc" ];
  boot.loader.grub.zfsSupport = true;
  boot.initrd.kernelModules = [ ];
  boot.supportedFilesystems = [ "zfs" ];
  boot.initrd.supportedFilesystems = [ "zfs" ];
  # acpi_call only for laptops
  boot.kernelModules = [ "kvm-intel" "acpi_call" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ acpi_call ];

  # acpi_call only for laptops
  # boot.extraModulePackages = with config.boot.kernelPackages; [ acpi_call ];

  fileSystems."/" =
    { device = "master/local/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "master/local/nix";
      fsType = "zfs";
    };

  fileSystems."/tmp" =
    { device = "master/local/tmp";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6A1D-C929";
      fsType = "vfat";
    };

  fileSystems."/persist" =
    { device = "master/safe/persist";
      fsType = "zfs";
      neededForBoot = true;
    };

  fileSystems."/home" =
    { device = "master/safe/home";
      fsType = "zfs";
    };

  fileSystems."/tomb" =
    { device = "master/safe/tomb";
      fsType = "zfs";
      neededForBoot = true;
    };

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  boot.extraModprobeConfig = ''
    # From https://unix.stackexchange.com/questions/572962/system-setting-to-stop-wifi-from-dropping-connection and https://bugzilla.kernel.org/show_bug.cgi?id=203709
    options mac80211 probe_wait_ms=2000 beacon_loss_count=30 max_nullfunc_tries=20 max_probe_tries=50
    options iwlwifi bt_coex_active=0
  '';
}
