# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.plymouth.enable = true;
  boot.initrd.systemd.enable = true;
  boot.initrd.availableKernelModules = 
    [ 
      "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" 

#      "intel_lpss_pci" "pinctrl_tigerlake" "surface_aggregator_registry" "surface_hid"  "surface_aggregator"
"intel_lpss_pci" "pinctrl_tigerlake" "8250_dw" "surface_aggregator" "surface_aggregator_hub" "surface_hid" "surface_hid_core" "i915"
#      "8250_dw" "surface_hid_core"
#      "i2c_hid_acpi" "hid_generic" "usbhid"
#      "intel_lpss" "serio_raw" "atkbd"
#      "i2c_designware_platform" "i2c_designware_core" "hid_multitouch" "hid_generic"
#      "intel_ish_ipc" "intel_ishtp_hid" "i915"
    ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
#  boot.consoleLogLevel = 7;
#  boot.kernelParams = [ "debug" ];
  boot.kernelParams = [ "i915.fastboot=1" ];

  fileSystems."/" =
    { device = "/dev/mapper/root";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/24d9d121-a269-437f-925f-ba3c00c1cd67";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0649-243E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/603B-9E49";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

