# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  - &paul 2A4F0026730E0C45C031B3FA2BF9A72A4A1D161D
  - &sorlag age1a0c8jmahvfppjqqy4375w4nq8knv0esshjx8kgdnpx6vl2djzfcsr8gdmg
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *paul
      age:
      - *sorlag
