# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.loader.efi.canTouchEfiVariables = true;
  boot.kernelParams = pkgs.lib.mkDefault [ "acpi_rev_override" ];

  boot.initrd.availableKernelModules = [ "usbhid" "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  # acpi_call only for laptops
  boot.kernelModules = [ "kvm-intel" "acpi_call" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ acpi_call ];

  # acpi_call only for laptops
  # boot.extraModulePackages = with config.boot.kernelPackages; [ acpi_call ];


  fileSystems."/" =
    { device = "/dev/mapper/slash";
    };

  boot.initrd.luks.devices."slash".device = "/dev/disk/by-uuid/c989b0da-9355-4de6-b13c-f0bfea57aad1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/BOOT";
    };

#   hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  # hardware.video.hidpi.enable = lib.mkDefault true;

  boot.extraModprobeConfig = ''
    # From https://unix.stackexchange.com/questions/572962/system-setting-to-stop-wifi-from-dropping-connection and https://bugzilla.kernel.org/show_bug.cgi?id=203709
    options mac80211 probe_wait_ms=2000 beacon_loss_count=30 max_nullfunc_tries=20 max_probe_tries=50
    options iwlwifi bt_coex_active=0
  '';
}
