name: BuildAndCache

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clone repo
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # Install nix
      - uses: cachix/install-nix-action@v31
      - name: Cachix setup
        uses: cachix/cachix-action@v15
        with:
          name: paulvictor
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pushFilter: "(-source$ | nixpkgs\.tar\.gz$)"
      - name: BuildSystemConfigurations
        working-directory: ./nix
        run: nix build github:srid/devour-flake -L --no-link --print-out-paths --override-input flake  .
